version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
      docker: 18
  pre_build:
    commands:
    - echo Logging in to Amazon ECR...
    - aws --version
    - $(aws ecr get-login --region us-east-1 --no-include-email)
    
  build:
    commands:
    - echo Build started on `date`
    - echo Building Java
    - mvn clean
    - echo Building the docker image..
    - docker build -t pms-process-pension-repository-890387 .
    - docker tag pms-process-pension-repository-890387:final 156962844638.dkr.ecr.us-east-1.amazonaws.com/pms-process-pension-repository-890387:final
  post_build:
    commands:
    - echo Build completed on `date`
    - echo Pushing docker image
    - docker push 156962844638.dkr.ecr.us-east-1.amazonaws.com/pms-process-pension-repository-890387:final
    - echo Writting definition file
    - printf '[{"name":"auth-container","imageUri":"%s"}]' 156962844638.dkr.ecr.us-east-1.amazonaws.com/pms-process-pension-repository-890387:final > imagedefinitions.json
artifacts:
  files:
  - processpension-microservice/imagedefinitions.json